@CaliberFS.Template.Consumer_HostAddress = https://localhost:7187

GET {{CaliberFS.Template.Consumer_HostAddress}}/background/
Accept: application/json
###

PATCH {{CaliberFS.Template.Consumer_HostAddress}}/background/
Content-Type: application/json

{
  "IsEnabled": false
}